version: "3.7"
services:
    app:
        build:
            args:
                user: ShakilAhmmed
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: pet-shop
        container_name: pet-shop-application
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - database
        links:
            - database
        networks:
            - pet-shop-network
    nginx:
        image: nginx:alpine
        container_name: pet-shop-nginx
        restart: unless-stopped
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d/
        networks:
            - pet-shop-network
        depends_on:
            - database
            - phpmyadmin
    database:
        image: mysql:5.7
        container_name: pet-shop-database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - pet-shop-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pet-shop-phpmyadmin
        restart: unless-stopped
        tty: true
        depends_on:
            - database
        ports:
            - "${PMA_PORT}:80"
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 2048M
        networks:
            - pet-shop-network
networks:
    pet-shop-network:
        driver: bridge
